FROM quay.io/farrion/python3-ml:latest

LABEL MAINTAINER="Mitesh Patel <mitpatel@redhat.com>"

COPY ./recommendation_engine /recommendation_engine
COPY ./requirements.txt /requirements.txt
COPY ./entrypoint.sh /bin/entrypoint.sh

RUN pip3 install -r requirements.txt

# --------------------------------------------------------------------------------------------------
# copy testing source code and scripts into root dir /
# --------------------------------------------------------------------------------------------------
ADD ./training/ /training
ADD ./tests/ /tests
ADD ./tests/scripts/entrypoint-test.sh /entrypoint-test.sh
# ADD .coveragerc /.coveragerc
# ADD ./.git /.git
ADD ./tools /tools
RUN chmod 0777 /entrypoint-test.sh

ENV PYTHONPATH=/

RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-rudra#egg=rudra
RUN pip3 install pytest pytest-cov radon==2.4.0 codecov

ENV USE_CLOUD_SERVICES="false"
ENV LOCAL_ACCESS="false"

# --------------------------------------------------------------------------------------------------
# RUN THE UNIT TESTS
# --------------------------------------------------------------------------------------------------
ENTRYPOINT ["/entrypoint-test.sh"]
